### ISSUE TITLE
Customized set control background picture interface

### ISSUE THREAD

**Issue by drearyrainDeng** [MicrosoftEdge/WebView2Feedback#1725]
Will there be an opportunity to add an interface for setting a background image? Like the button control of winform

**Comment by d2phap** [comment]
Why don't you use CSS
```css
body {
  background-image: url('______');
}
```
