### ISSUE TITLE
Please fix or support the CSS variables in ::selection

### ISSUE THREAD

**Issue by alengYuan** [MicrosoftEdge/WebView2Feedback#3370]
CSS variables defined in `:root` could be used in any normal element, but I found it can't be used in `::selection`, such as `input::selection`.

In fact, it could work in Chrome but not Edge (of course, and WebView2 in WinUI3).

The code works as expected in Chrome 111.0.5563.147.

![chrome](https://user-images.githubusercontent.com/25302878/230709896-8f73ae59-5f30-49b9-9661-97599d46e927.png)

Edge 111.0.1661.62 shows that it can't find the variables have been defined in `:root`.

![edge01](https://user-images.githubusercontent.com/25302878/230709884-0b4c35c0-6f72-46e9-9c91-b2242d5d867d.png)

![edge02](https://user-images.githubusercontent.com/25302878/230709891-6250509b-e195-4446-892a-f428811c66f3.png)

These are code used to test:

```html
<input>
<div contenteditable="plaintext-only"></div>
```

```css
:root {
  --bg: red;
}

div {
  display: flex;
  align-items: center;
  width: 200px;
  height: auto;
  border: 1px black solid;
  font-size: 14px;
  padding: 2px;
}

input::selection {
  background-color: var(--bg);
  color: #800080;
}

div::selection {
  background-color: var(--bg);
  color: #800080;
}
```

I'm not sure if this is a Chrome-exclusive feature, but intuitively I think it's something that should be implemented, so please fix or support it.
